/* eslint-disable no-unused-vars */
export enum LOCAL_STORAGE_KEYS {
  ID_USER = 'TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  IP_ADDRESS = 'IP_ADDRESS',
  DEVICE_NAME = 'DEVICE_NAME',
  LANGUAGE = 'LANGUAGE',
  NAME_USER = 'NAME_USER',
  EMAIL_USER = 'EMAIL_USER',
  ADDRESS_USER = 'ADDRESS_USER',
  SEARCH_FEED = 'SEARCH_FEED',
  SEARCH_FEED_FOR_SALE = 'SEARCH_FEED_FOR_SALE',
}
